# Generated by Django 4.2.6 on 2023-10-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(default='pfps/def_pfp.jpg', upload_to='pfps'),
        ),
    ]
