# Generated by Django 4.2.6 on 2023-11-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_moderator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderator',
            old_name='can_approve_runs',
            new_name='can_validate_runs',
        ),
    ]
