# Generated by Django 4.2.6 on 2023-12-03 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_can_approve_runs_moderator_can_validate_runs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('reason', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.moderator')),
            ],
            options={
                'verbose_name': 'ban',
                'verbose_name_plural': 'bans',
            },
        ),
    ]
