# Generated by Django 4.2.6 on 2023-11-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'game', 'verbose_name_plural': 'games'},
        ),
    ]
