# Generated by Django 4.2.6 on 2023-11-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedcategory',
            name='extra_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
