# Generated by Django 4.2.6 on 2023-11-05 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_alter_game_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
            ],
            options={
                'verbose_name': 'allowed category',
                'verbose_name_plural': 'allowed categories',
                'unique_together': {('game', 'category')},
            },
        ),
    ]
