# Generated by Django 4.2.6 on 2023-11-12 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_allowedcategory_extra_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime_ms', models.PositiveIntegerField()),
                ('video_link', models.CharField(max_length=100)),
                ('time_upoaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('game_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.allowedcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'run',
                'verbose_name_plural': 'runs',
            },
        ),
    ]
