# Generated by Django 4.2.6 on 2023-11-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_allowedcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='banner',
            field=models.ImageField(default='default_game_banner.jpg', upload_to='game_banners'),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(default='default_game_icon.jpg', upload_to='games_icons'),
        ),
    ]
