# Generated by Django 4.2.6 on 2023-11-14 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'refuse',
                'verbose_name_plural': 'refuses',
            },
        ),
        migrations.AddField(
            model_name='run',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
