# Generated by Django 4.2.6 on 2023-11-14 08:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_moderator'),
        ('main', '0005_refuse_moderator_refuse_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='is_validated',
        ),
        migrations.CreateModel(
            name='Validations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.moderator')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.run')),
            ],
        ),
    ]
