# Generated by Django 4.2.6 on 2023-11-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_moderator'),
        ('main', '0006_remove_run_is_validated_validations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Validations',
            new_name='Validation',
        ),
    ]
