# Generated by Django 4.2.6 on 2023-11-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_validations_validation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validation',
            options={'verbose_name': 'validation', 'verbose_name_plural': 'validations'},
        ),
        migrations.RenameField(
            model_name='run',
            old_name='time_upoaded',
            new_name='time_uploaded',
        ),
    ]
