# Generated by Django 4.2.6 on 2023-11-14 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_validation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuse',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.run', unique=True),
        ),
        migrations.AlterField(
            model_name='validation',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.run', unique=True),
        ),
    ]
