# Generated by Django 4.2.6 on 2023-11-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_refuse_id_remove_validation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='is_refused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='run',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
