# Generated by Django 4.2.6 on 2023-11-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_moderator'),
        ('main', '0011_run_is_refused_run_is_validated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refuse',
            new_name='Reject',
        ),
        migrations.RenameField(
            model_name='run',
            old_name='is_refused',
            new_name='is_rejected',
        ),
    ]
