# Generated by Django 4.2.6 on 2023-11-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_moderator'),
        ('main', '0012_rename_refuse_reject_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reject',
            new_name='Rejection',
        ),
    ]
