# Generated by Django 4.2.6 on 2023-11-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_reject_rejection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejection',
            options={'verbose_name': 'rejection', 'verbose_name_plural': 'rejections'},
        ),
    ]
