# Generated by Django 4.2.6 on 2023-11-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_rejection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
