# Generated by Django 4.2.6 on 2023-12-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_comment_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejection',
            name='run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rejection', serialize=False, to='main.run'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='validation', serialize=False, to='main.run'),
        ),
    ]
